name: opencongopay
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

  sqflite: ^2.4.3
  path_provider: ^2.1.6
  local_auth: ^3.0.2
  shared_preferences: ^2.5.5
  flutter_bloc: ^9.1.1
  opentelemetry: ^0.18.11
  path: ^1.9.1
  crypto: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  test: any

flutter:
  uses-material-design: true
